networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=odoo-shop.dy
      - VIRTUAL_PORT=8069
      - DEMO=False
      - WORKERS=4
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/bank-payment,/odoo/external-src/crm,/odoo/external-src/delivery-carrier,/odoo/external-src/e-commerce,/odoo/external-src/product-brand,/odoo/external-src/product-variant,/odoo/external-src/queue,/odoo/external-src/sale-workflow,/odoo/external-src/ak-odoo-incubator,/odoo/external-src/connector-search-engine,/odoo/external-src/odoo-shopinvader,/odoo/external-src/rest-framework,/odoo/external-src/payment-gateway,/odoo/external-src/server-tools,/odoo/external-src/storage,external-src/connector,/odoo/external-src/shopinvader
    links:
      - db
      - pgadmin
    networks:
      default:
        aliases:
          - odoo-shop.dy
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
  pgadmin:
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASSWORD=admin
      - VIRTUAL_HOST=pgadmin.odoo-shop.dy
      - VIRTUAL_PORT=5050
    image: fenglc/pgadmin4
    links:
      - db
    networks:
      default:
        aliases:
          - pgadmin.odoo-shop.dy
version: '3'
